# render.yaml

services:
  - type: web
    name: fraud-detection-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.port 10000
    plan: free
    envVars:
      - key: MONGO_URI
        value: <your MongoDB Atlas connection string>
